### ISSUE TITLE
Chrome & Brave browsers doesn't render the icons

### ISSUE THREAD

**Issue by AdrianKBL** [danalloway/detect-emoji-support#5]
Hello!

With Firefox I don't have any problems, but with Chrome and Brave , isn't working. Gonna post you Screnshoots.

Any ETA to fix it?

Im using Windows 11 x64

![image](https://user-images.githubusercontent.com/59306428/174896807-72eec951-417a-40bc-8065-b0ca3a164774.png)
![image](https://user-images.githubusercontent.com/59306428/174896825-2a3ea034-2954-4697-9716-544059e4769c.png)

**Comment by danalloway** [comment]
@AdriMsM91 this library doesn't render icons it only detects emoji support using ported code from Modernizr https://github.com/Modernizr/Modernizr/blob/master/feature-detects/emoji.js
